"C:/Program Files/Inkscape/Inkscape.exe" --export-dpi=300 --export-png=output/runde0.png output/runde0.svg
"C:/Program Files/Inkscape/Inkscape.exe" --export-dpi=300 --export-png=output/runde1.png output/runde1.svg
"C:/Program Files/Inkscape/Inkscape.exe" --export-dpi=300 --export-png=output/runde2.png output/runde2.svg
"C:/Program Files/Inkscape/Inkscape.exe" --export-dpi=300 --export-png=output/runde3.png output/runde3.svg
"C:/Program Files/Inkscape/Inkscape.exe" --export-dpi=300 --export-png=output/runde4.png output/runde4.svg
"C:/Program Files/Inkscape/Inkscape.exe" --export-dpi=300 --export-png=output/runde5.png output/runde5.svg
"C:/Program Files/Inkscape/Inkscape.exe" --export-dpi=300 --export-png=output/runde6.png output/runde6.svg
"C:/Program Files/Inkscape/Inkscape.exe" --export-dpi=300 --export-png=output/runde7.png output/runde7.svg
"C:/Program Files/Inkscape/Inkscape.exe" --export-dpi=300 --export-png=output/runde8.png output/runde8.svg
"C:/Program Files/Inkscape/Inkscape.exe" --export-dpi=300 --export-png=output/runde9.png output/runde9.svg
"C:/Program Files/Inkscape/Inkscape.exe" --export-dpi=300 --export-png=output/runde10.png output/runde10.svg
"C:/Program Files/Inkscape/Inkscape.exe" --export-dpi=300 --export-png=output/runde11.png output/runde11.svg
"C:/Program Files/Inkscape/Inkscape.exe" --export-dpi=300 --export-png=output/runde12.png output/runde12.svg
"C:/Program Files/Inkscape/Inkscape.exe" --export-dpi=300 --export-png=output/runde13.png output/runde13.svg
"C:/Program Files/Inkscape/Inkscape.exe" --export-dpi=300 --export-png=output/runde14.png output/runde14.svg
"C:/Program Files/Inkscape/Inkscape.exe" --export-dpi=300 --export-png=output/runde15.png output/runde15.svg